# Generated by Django 5.0.4 on 2026-06-03 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('status_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('incident_created', 'Incident created'), ('incident_updated', 'Incident updated'), ('incident_resolved', 'Incident resolved')], max_length=25)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error', models.TextField(blank=True, default='', help_text='Error detail if delivery failed.')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='incidents.incident')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='status_pages.subscriber')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', 'event_type'], name='idx_notiflog_incident_event'), models.Index(fields=['delivery_status', 'created_at'], name='idx_notiflog_status_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('incident', 'subscriber', 'event_type'), name='uniq_notification_incident_subscriber_event'),
        ),
    ]
