# Generated by Django 5.0.4 on 2026-06-01 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Public name shown at the top of the status page.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Forms the public URL. Lowercase, hyphens only. Immutable after creation.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase alphanumeric with hyphens only. Must start and end with a letter or number. Example: 'acme-api'", regex='^[a-z0-9][a-z0-9\\-]*[a-z0-9]$')])),
                ('description', models.TextField(blank=True, default='', help_text='Optional public description shown below the page title.')),
                ('brand_color', models.CharField(default='3B82F6', help_text='6-digit hex color code (without #) for the page accent.', max_length=6)),
                ('theme', models.CharField(choices=[('system', 'System default'), ('custom', 'Custom color')], default='system', help_text='Color theme for the public page.', max_length=10)),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='When False, the page is not accessible to the public.')),
                ('show_beacon_branding', models.BooleanField(default=True, help_text="Show 'Powered by Beacon' badge on the public page.")),
                ('allow_subscriptions', models.BooleanField(default=True, help_text='Allow visitors to subscribe for incident notifications.')),
                ('custom_domain', models.CharField(blank=True, default='', help_text="Custom domain for this status page. e.g. 'status.acme.com'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user account this status page belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='status_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Page',
                'verbose_name_plural': 'Status Pages',
                'db_table': 'status_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', help_text="Public-facing name for this monitor on the status page. Falls back to the monitor's internal name if blank.", max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order. Lower numbers appear first.')),
                ('show_uptime_history', models.BooleanField(default=True, help_text='Show the 90-day uptime history bar for this monitor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(help_text='The monitor being displayed.', on_delete=django.db.models.deletion.CASCADE, related_name='status_page_entries', to='monitors.monitor')),
                ('status_page', models.ForeignKey(help_text='The status page this monitor appears on.', on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='status_pages.statuspage')),
            ],
            options={
                'verbose_name': 'Status Page Monitor',
                'verbose_name_plural': 'Status Page Monitors',
                'db_table': 'status_page_monitors',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], help_text='The channel through which notifications are delivered.', max_length=10)),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='Telegram chat ID. Required for telegram channel.', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address. Required for email channel.', max_length=254)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used in unsubscribe URLs. Never changes.', unique=True)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, help_text='Only confirmed subscribers receive notifications.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When False, no notifications are sent. Set on unsubscribe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_page', models.ForeignKey(help_text='The status page this subscription is for.', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='status_pages.statuspage')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='statuspage',
            index=models.Index(fields=['slug'], name='idx_statuspage_slug'),
        ),
        migrations.AddIndex(
            model_name='statuspage',
            index=models.Index(fields=['owner', '-created_at'], name='idx_statuspage_owner_created'),
        ),
        migrations.AddIndex(
            model_name='statuspage',
            index=models.Index(fields=['slug', 'is_public'], name='idx_statuspage_slug_public'),
        ),
        migrations.AddIndex(
            model_name='statuspagemonitor',
            index=models.Index(fields=['status_page', 'display_order'], name='idx_spm_page_order'),
        ),
        migrations.AlterUniqueTogether(
            name='statuspagemonitor',
            unique_together={('status_page', 'monitor')},
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['status_page', 'notification_channel', 'is_confirmed', 'is_active'], name='idx_subscriber_page_channel_active'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['unsubscribe_token'], name='idx_subscriber_unsubscribe_token'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('notification_channel', 'telegram')), fields=('status_page', 'telegram_chat_id'), name='uniq_subscriber_telegram_per_page'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('notification_channel', 'email')), fields=('status_page', 'email'), name='uniq_subscriber_email_per_page'),
        ),
    ]
