# Generated by Django 5.0.4 on 2026-06-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_pages', '0002_statuspage_slack_webhook_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriber',
            new_name='idx_sub_page_channel_active',
            old_name='idx_subscriber_page_channel_active',
        ),
        migrations.RenameIndex(
            model_name='subscriber',
            new_name='idx_sub_unsubscribe_token',
            old_name='idx_subscriber_unsubscribe_token',
        ),
    ]
