# Generated by Django 5.0.4 on 2026-06-01 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name. e.g. 'CI/CD Pipeline' or 'Zapier Integration'.", max_length=100)),
                ('prefix', models.CharField(editable=False, help_text='First 12 characters of the key for display. Not secret.', max_length=12)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 hash of the full key. Never the raw key.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When False, this key is rejected on authentication.')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this key was revoked. Null if still active.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this key expires. Null = never expires.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last successful authentication timestamp.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user this key authenticates as.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash', 'is_active'], name='idx_apikey_hash_active'), models.Index(fields=['owner', '-created_at'], name='idx_apikey_owner_created')],
            },
        ),
    ]
