# Generated by Django 5.0.4 on 2026-06-01 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier. Safe to expose in URLs.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name. e.g. 'API Gateway' or 'Main Website'.", max_length=255)),
                ('monitor_type', models.CharField(choices=[('http', 'HTTP / HTTPS'), ('tcp', 'TCP Port'), ('ping', 'ICMP Ping')], default='http', help_text='The protocol used to check this monitor.', max_length=10)),
                ('url', models.URLField(blank=True, default='', help_text='The endpoint to monitor. Required for HTTP monitors.', max_length=2048)),
                ('host', models.CharField(blank=True, default='', help_text='Hostname or IP. Used for TCP and PING monitors.', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, help_text='TCP port number. Required for TCP monitors.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('interval', models.PositiveIntegerField(default=60, help_text='Check interval in seconds. Min: 30, Max: 86400 (24h).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)])),
                ('expected_status_codes', models.CharField(blank=True, default='200', help_text="Comma-separated HTTP status codes considered healthy. e.g. '200,201,204'. HTTP monitors only.", max_length=100)),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds. Min: 1, Max: 60.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('outage', 'Outage'), ('paused', 'Paused'), ('pending', 'Pending first check')], db_index=True, default='pending', help_text='Current operational status. Denormalized from latest check.', max_length=15)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When False, no checks are performed. Status becomes PAUSED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent completed check.', null=True)),
                ('owner', models.ForeignKey(help_text='The user account this monitor belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitors',
                'db_table': 'monitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('timeout', 'Timeout'), ('error', 'Error')], help_text='Outcome of this check.', max_length=10)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip response time in milliseconds.', null=True)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code returned by the endpoint.', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error detail if status is DOWN, TIMEOUT, or ERROR.')),
                ('region', models.CharField(default='local', help_text='Region or location where this check originated.', max_length=50)),
                ('checked_at', models.DateTimeField(db_index=True, help_text='UTC timestamp when this check completed.')),
                ('monitor', models.ForeignKey(help_text='The monitor this check belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.monitor')),
            ],
            options={
                'verbose_name': 'Monitor Check',
                'verbose_name_plural': 'Monitor Checks',
                'db_table': 'monitor_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['is_active', 'status'], name='idx_monitor_active_status'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['owner', '-created_at'], name='idx_monitor_owner_created'),
        ),
        migrations.AddIndex(
            model_name='monitorcheck',
            index=models.Index(fields=['monitor', '-checked_at'], name='idx_check_monitor_time'),
        ),
        migrations.AddIndex(
            model_name='monitorcheck',
            index=models.Index(fields=['monitor', 'status', '-checked_at'], name='idx_check_monitor_status_time'),
        ),
    ]
