# Generated by Django 5.0.4 on 2026-06-01 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier. Used in status page URLs.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Short description. e.g. 'API Gateway — Elevated Error Rate'.", max_length=255)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], db_index=True, default='investigating', help_text='Current lifecycle stage of this incident.', max_length=15)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('notice', 'Notice')], db_index=True, default='minor', help_text='Impact severity. Independent of lifecycle status.', max_length=10)),
                ('summary', models.TextField(blank=True, default='', help_text='Optional public-facing summary of the incident. Shown on the status page above the update feed.')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='When True, this incident appears on the public status page. Set to False to investigate privately before publishing.')),
                ('auto_created', models.BooleanField(default=False, help_text='True if created automatically by the monitor checker worker.')),
                ('started_at', models.DateTimeField(help_text='When the incident started. May be backdated.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the incident was resolved. Null if still active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user account this incident belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitor_status_snapshot', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('outage', 'Outage'), ('paused', 'Paused'), ('pending', 'Pending first check')], help_text="The monitor's status at the time it was linked to this incident.", max_length=15)),
                ('recovered_at', models.DateTimeField(blank=True, help_text='When this monitor recovered. Null if still affected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='The incident this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='affected_monitors', to='incidents.incident')),
                ('monitor', models.ForeignKey(help_text='The monitor affected by this incident.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
            options={
                'verbose_name': 'Incident Monitor',
                'verbose_name_plural': 'Incident Monitors',
                'db_table': 'incident_monitors',
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_at_update', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], help_text='Incident status at the time this update was posted.', max_length=15)),
                ('message', models.TextField(help_text='The update message. Plain text. Markdown support coming in Phase 03.')),
                ('is_public', models.BooleanField(default=True, help_text='When False, this update is only visible to team members.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='The incident this update belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
                ('posted_by', models.ForeignKey(blank=True, help_text='Team member who posted this update. Null if automated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Update',
                'verbose_name_plural': 'Incident Updates',
                'db_table': 'incident_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['owner', 'status', 'is_public'], name='idx_incident_owner_status_public'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['owner', '-started_at'], name='idx_incident_owner_started'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='idx_incident_status_severity'),
        ),
        migrations.AddIndex(
            model_name='incidentmonitor',
            index=models.Index(fields=['incident', 'monitor'], name='idx_incidentmonitor_incident_monitor'),
        ),
        migrations.AddIndex(
            model_name='incidentmonitor',
            index=models.Index(fields=['monitor', '-created_at'], name='idx_incidentmonitor_monitor_created'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentmonitor',
            unique_together={('incident', 'monitor')},
        ),
        migrations.AddIndex(
            model_name='incidentupdate',
            index=models.Index(fields=['incident', '-created_at'], name='idx_update_incident_created'),
        ),
        migrations.AddIndex(
            model_name='incidentupdate',
            index=models.Index(fields=['incident', 'is_public', '-created_at'], name='idx_update_incident_public_created'),
        ),
    ]
