# Generated by Django 5.0.4 on 2026-06-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incident',
            new_name='idx_inc_owner_status_public',
            old_name='idx_incident_owner_status_public',
        ),
        migrations.RenameIndex(
            model_name='incidentmonitor',
            new_name='idx_im_incident_monitor',
            old_name='idx_incidentmonitor_incident_monitor',
        ),
        migrations.RenameIndex(
            model_name='incidentmonitor',
            new_name='idx_im_monitor_created',
            old_name='idx_incidentmonitor_monitor_created',
        ),
        migrations.RenameIndex(
            model_name='incidentupdate',
            new_name='idx_update_inc_public_created',
            old_name='idx_update_incident_public_created',
        ),
    ]
